import { Hd } from "../components/comUtil/ComUtil";
import Main from "../components/Main";

export default function Home({title}) {
  return (
    <>
      <Hd title={title} >
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Hd>

      <Main />
    </>
  );
}


export async function getStaticProps() {
  return {
    props: {title: 'القائمة الرئيسية'},
  }
}
