import { Hd } from "../components/comUtil/ComUtil";
import Main from "../components/Main";

export default function Home() {
  return (
    <>
      <Hd title='القائمة الرئيسية' >
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Hd>

      <Main />
    </>
  );
}
